apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

bases:
  - ../../base

nameSuffix: -dev

replicas:
  - name: cliet-tableaux-angular
    count: 1

resources:
  - namespace.yaml

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: app-image
    newName: ghcr.io/benjaliette/cliet-tableaux-angular
    newTag: develop
