apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cliet-tableaux-angular
spec:
  rules:
  - host: www.cliet-tableaux.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cliet-tableaux-angular
            port:
              number: 80
