apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

nameSuffix: -prod

replicas:
- count: 3
  name: cliet-tableaux-angular

resources:
- ../../base
- namespace.yaml
- middleware.yaml

patchesStrategicMerge:
- ingress-patch.yaml

images:
- name: cliet-tableaux-angular
  newName: ghcr.io/benjaliette/cliet-tableaux-angular
  newTag: latest
