apiVersion: v1
kind: Service
metadata:
  name: cliet-tableaux-angular
  namespace: cliet-tableaux
spec:
  selector:
    app: cliet-tableaux-angular
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
